### ISSUE TITLE
Compulsory Equipment

### ISSUE THREAD

**Issue by JArnbak** [qpit/Lab-Management#1]
**The Idea:**

-	Every optical table needs a number of basic pieces of equipment in order to work optimally.
-	Moving these components between labs drastically increases the risk of component misplacement.
-	Therefore, we need to make sure that every optical table in every lab has the required components to make sure that people never have to borrow these components from each other.
-	If a component (e.g. power or multimeter) is to be permanently integrated into an experiment, then that component should be bought specifically for that project independently of the compulsory part.
-	The component list includes items for each table and items common for each lab (still compulsory)

**Comment by JArnbak** [comment]
**Compulsory items (for each table in the lab):**
- [x] Power meter + sensor heads for each color. 
- [x] Multimeter + probes. 
- [x] Fiberscope. 
- [x] Viewer cards for each color. 
- [x] Alignment tools for each beam height and each color. 
- [x] Assortment of screwdrivers and hex keys. 
 - M6, M4, M3, M2.5, M2, M1.5, etc. 
- [x] Laser googles for each color. 
- [x] Beam dumps and blocks for each beam height. 
- [x] Label printer. 
- [x] Calipers + measurement tapes. 
- [x] Elephant feet.

**Comment by JArnbak** [comment]
**Compulsory items (for each lab):**
- [x] Gloves. 
- [x] Hairnet. 
- [x] Equipment for cleaning and mounting optics. 
 - Tweezers (with and without rubber tips). 
 - Forceps (with and without lock). 
 - Alcohol. 
 - Clean, pressurized air. 
 - Cleaning tissues. 
 - Spanner Wrenches. 
 - Fiber cleaning box.

**Comment by JArnbak** [comment]
**To-do:**
- [x] Confirm with PIs.
- [x] Get overview of lab equipment status.
- [x] Order commercial equipment.
- [x] Order local items (beam blocks, alignment tools etc).
- [x] Distribute to each lab.
- [x] Profit!

**Comment by JArnbak** [comment]
Missing item:

Power meter + sensor heads for each color.
- consoles [2 x **computing**, 2 x **cat**, 1 x **spin**, 1 x **crypto**]
- sensor heads
   - Visible 400-1100 nm [1 x **spin**]
   - IR 950-1600 nm [1 x **attocube**, 2 x **computing**, 1 x **cat**, 1 x **crypto**]
- Couplers for FC/PC [2 x **cat**, 2 x **crypto**]
- Couplers for FC/APC [2 x **cat**, 2 x **crypto**]

Multimeter + probes. (ideally measure capacitance)
- [1 x **attocube**, 1 x **diamond**, 1 x **CV**, 1 x **computing**, 2 x **cat**, 1  x **crypto**]

Fiberscope.
- [1 x **diamond**, 1 x **cat**]
- LR44 Batteries [**all**]

Viewer cards for each color.
- 532 [1 x **CV**]
- 1550 [1 x **CV**, 1 x **archive**, 4 x **cat**, 2 x **crypto**]
- 775 [1 x **CV**, 4 x **cat**] 

Alignment tools for each beam height and each color.
- 90 mm [3 x 980 nm **attocube**, 3 x 1550 nm **archive**]
- 83 mm [3 x 530 nm **attocube**]
- 65 mm [3 x 1550 nm **computing**, 3 x 775 nm **computing**]
- 75 mm [4 x 1550 nm **cat**, 4 x 1550 nm **crypto**]

Assortment of screwdrivers and hex keys.
M6, M4, M3, M2.5, M2, M1.5, etc.
- [1 x **Micro**, 1 x **CV**, 1 x **cat**]
- extra M6 [1 x **all**]

Laser googles for each color.
- 300 nm [1 x **spin**]
- 532 nm [3 x **attocube**, 3 x **diamond**, 2 x **spin**]
- 450 nm [3 x **diamond**]
- 650 nm [3 x **diamond**]
- 1550 nm [BGKG](https://phillips-safety.com/product-category/laser/laser-safety-glasses/bgkg/?page=1) [1 x **micro**, 3 x **archive**, 5 x **cat**, 2 x **crypto**]

Beam dumps and blocks for each beam height.
- 90 mm [10 x **attocube**, 5 x **archive**]
- 83 mm [10 x **attocube**]
- 65 mm [20 x **computing**]
- 75 mm [20 x **cat**, 10 x **crypto**]
- [LB1/M](https://www.thorlabs.com/thorproduct.cfm?partnumber=LB1/M) [4 x **spin**]

Label printer.
- [1 x **attocube**, 1 x **diamond**, 1 x **cat**, 1 x **spin**]

Calipers + measurement tapes.
- Calipers [1 x **attocube**, 1 x **diamond**, 1 x **CV**, 1 x **archive**, 1 x **computing**, 1 x **spin**, 1 x **crypto**]
- measurement tapes [1 x **attocube**, 1 x **diamond**, 1x **CV**, 2 x **cat**, 2x **spin**]

Elephant feet.
- [3 x **cat**, 2 x **spin**]

Gloves.
- [**archive**, **crypto**]

Hairnet.
- [**attocube**, **diamond**, **archive**, **cat**, **crypto**]

Equipment for cleaning and mounting optics.

Tweezers (with and without rubber tips).
- Hard tip [2 x **cat**, 1 x **crypto**]
- Soft tip [2 x **cat**, 1 x **crypto**]

Forceps (with and without lock).
- Straight tip  w. lock [1 x **archive**, 1 x **cat**, 1 x **crypto**]
- Straight tip  w/o. lock [1 x **archive**, 1 x **cat**, 1 x **crypto**]

Alcohol.
- [**attocube**, **crypto**]

Clean, pressurized air.
- [**attocube**, **archive**, **cat**,  **crypto**]

Cleaning tissues.
- [**archive**,  **crypto**]

Spanner Wrenches.
- [1 x **attocube**, 1 x **diamond**, 1 x **CV**, 1 x **cat**, 1 x **spin**,  1 x **crypto**]

Fiber cleaning box.
- [1 x **archive**, 2 x **cat**]

 [Infrared hand-held viewer](https://www.newport.com/f/infrared-viewers)
- [**all**]

Small Ladder
- [**all** - **CV**]

replies received:
CV
computing
micro
attocube
diamond
archive
storage
cat
spin
crypto

**Comment by JArnbak** [comment]
Beam Dumps are wrong height! 
We are missing the final couple of items!
- [x] Forceps w/o lock
- [ ] Googles
- [x] Fiber Clean Box
- [x] Viewercard @ 775
- [x] LB1/M
