### ISSUE TITLE
Cleaning Standards

### ISSUE THREAD

**Issue by JArnbak** [qpit/Lab-Management#2]
**The Idea:**
- Common for all labs, weekly cleaning in pairs.
- I will set up a pairing and reminder system for each lab.
- Every lab should have a stock of lab coats, hairnets and gloves.
  - CVLAB will still function as a central hub for coats.
- Each lab will have an electrical vacuum cleaner to cover both floor and surface cleaning.
- Corridor cleaning will start including everyone (theoreticians included).
  - Everyone will spend 20 min / half year. 
- I will take over organizing corridor cleaning.
- I will take over responsibility for stocking mats, shoe covers etc.

**Comment by JArnbak** [comment]
**Lab cleaning: (Duration should be around 20 min / week.)**
- Sweeping the floors (dry).
- Wiping the surfaces.
- Changing sticky mats.
- Emptying bins.
- Tidying up unused equipment.
- Fill the stock of lab coats from CVLAB.

**Comment by JArnbak** [comment]
**Corridor cleaning: (Duration should be around 20 min / week)**
-	Wiping shoe shelves.
-	Changing sticky mats.
-	Empty all labs of used coats and bring it to the pick-up point next to the elevator (before Monday at 5 pm).
-	Tuesday morning pick up clean coats and bring to CVLAB.

**Comment by JArnbak** [comment]
**To-do:**
- [x] Feedback from PIs.
- [x] Purchase sweepers.
- [x] Distribute sweepers.
- [x] Stock up on mats, shoe covers and dust-cloths.
- [x] Organize lab cleaning.

**Comment by JArnbak** [comment]
**Vacuum Cleaner**
- The cleaner should have a HEPA filter.
- The cleaner should be at least 2-1 to allow for both surface and floor cleaning. 
- Cheap option: [iiglo Håndholdt Premium Støvsuge](https://www.komplett.dk/product/1204451/bolig-fritid/stoevsugere-rengoering/ledningsfrie-stoevsugere/iiglo-haandholdt-premium-stoevsuger#technical-details)
- More expensive options: [Miele vacuum cleaners](https://www.miele.dk/category/1268048/ledningsfri-stovsuger?page=1&query=:st_01_005:0_st_01_005_20)

Open question:
- what budget can I get to buy vacuum cleaners?
- Should we buy one for each lab or have a range of vacuum cleaners that we share across multiple labs ?

**Comment by JArnbak** [comment]
Received quotes for 14 vacuum cleaners (3 for the new 313 labs, 10 for existing labs
 and 1 for the downstairs workshop)
[Miele_15726727.pdf](https://github.com/user-attachments/files/16863019/Miele_15726727.pdf)
[Miele_15726728.pdf](https://github.com/user-attachments/files/16863020/Miele_15726728.pdf)
