### ISSUE TITLE
Organize (Downstairs) workshop

### ISSUE THREAD

**Issue by JArnbak** [qpit/Lab-Management#3]
**The Idea:**
-	The downstairs workshop is quite messy and has a lot of old / unused / undesirable equipment.
-	If cleaned and tidied up properly, the room could be a great place for storing unused optics, optomechanical and fiber equipment.

**Comment by JArnbak** [comment]
**To-do:**
- [x] Feedback from PIs.
- [x] Decide on the fate of old equipment.
- [x] Clear out / donate / give away undesirable equipment.
- [x] Tidy up and clean the room.
- [x] Make room for proper storage of useful equipment.
