### ISSUE TITLE
Chemistry Documentation

### ISSUE THREAD

**Issue by JArnbak** [qpit/Lab-Management#9]
**The Idea:** 
-	The sample prep room has multiple types of chemicals, some of which are not registered within [Kemibrug](https://kemibrug.dk/).
-	Furthermore, some of the chemicals do not have proper documentation and some processes do not have risk assessments attached to them.

**Comment by JArnbak** [comment]
**To-do:**
- [x] Contact and have Jacqueline help with getting an overview of chemicals in the prep room.
- [x] Contact and have Jaqueline help with registering the chemicals in Kemibrug.
- [x] Contact and have Jaqueline help with making proper risk assessments.

**Comment by alexanderhuck** [comment]
I went through the room with Jacqueline twice this spring. Chemicals should be registered now, but storage cabinets need re-ordering and improved labeling.

**Comment by JArnbak** [comment]
@alexanderhuck does this also include risk assessments or just registration in kemibrug?

**Comment by alexanderhuck** [comment]
Risk assessments will have to be revised or newly done.

**Comment by JArnbak** [comment]
Updated to do: 
- [ ] Updated Risk assessment for tri-acid cleaning proceedure
- [ ] Registration of the 6 chemical cupboards in kemibrug
- [ ] Registration of chamicals in kemibrug
